FROM openjdk:11-jre-slim-buster
VOLUME /tmp
EXPOSE 8080
ADD EmployeeManagement-0.0.1-SNAPSHOT.jar EmployeeManagement-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","EmployeeManagement-0.0.1-SNAPSHOT.jar"]